# Generated by Django 3.2.9 on 2021-11-18 09:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttAccount', '0002_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begDate', models.DateTimeField(default=datetime.datetime.now)),
                ('expDate', models.DateTimeField(default=datetime.datetime.now)),
                ('isFinished', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=200)),
                ('reward', models.IntegerField()),
                ('isTransferred', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_family', to='ttAccount.family')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'level1'), (2, 'level2'), (3, 'level3'), (4, 'level4'), (5, 'level5'), (6, 'level6'), (7, 'level7'), (8, 'level8'), (9, 'level9')])),
                ('score', models.IntegerField()),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_child', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
