# Generated by Django 3.2.9 on 2021-11-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='isFinished',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='isTransferred',
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.IntegerField(choices=[(0, 'fail'), (1, 'success'), (2, 'doing'), (3, 'finished')], default=2),
        ),
    ]
