# Generated by Django 3.2.9 on 2021-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
