# Generated by Django 3.2.9 on 2021-11-16 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trdd', models.CharField(max_length=8)),
                ('txtm', models.CharField(max_length=6)),
                ('mnrcDrotDsnc', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('tram', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('aftrBlnc', models.IntegerField()),
                ('bnprCntn', models.TextField()),
                ('tuno', models.IntegerField()),
            ],
        ),
    ]
