# Generated by Django 3.2.9 on 2021-11-21 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_analysis_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='aftrBlnc',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='mnrcDrotDsnc',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='trdd',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='txtm',
        ),
        migrations.AddField(
            model_name='analysis',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 21)),
        ),
    ]
