# Generated by Django 3.2.9 on 2021-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20211121_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date',
            field=models.DateField(),
        ),
    ]
