# Generated by Django 3.2.9 on 2021-11-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthda',
            field=models.CharField(default=19990221, max_length=8),
            preserve_default=False,
        ),
    ]
