# Generated by Django 3.2.9 on 2021-11-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttAccount', '0002_user_birthda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthda',
            new_name='birthday',
        ),
    ]
